#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := qf_wifi_server

#
# QuickLogic specific code
# 
EXTRA_COMPONENT_DIRS += $(PROJECT_PATH)/ql_components

include $(IDF_PATH)/make/project.mk

